- name: Lynis install and audit systems
  hosts: hosts #Put here your own group of hosts
  become: yes
  tasks:
  - name: Updating system
    yum:
     update_cache=yes
     state=latest

#Genreate ssh key on your ansible computer before with the command "ssh_keygen".

  - name: Generating ssh keys
    command: scp ~./ssh/id_rsa.pub user@ip_host:./ssh/authorized_keys

  - name: Get packages from GitHub
    command: git clone https://github.com/CISOfy/lynis

  - name: Execute Lynis
    command: cd ~/./lynis && ./lynis audit system

# The following steps is an extra if you want to get the Lynis report on a dedicated server

  - name: Rename Lynis log 
    command: /var/log/lynis.log > /var/log/{{ ansible_hostname }}-lynis.log #"ansible_hostname" var rename the file from the inventory file

  - name: Rename Lynis report
    command: /var/log/lynis-report.dat > /var/log/{{ ansible_hostname }}-lynis-report.dat

  - name: Send Lynis log
    copy:
     src: /var/log/{{ ansible_hostname }}-lynis.log
     dest: /etc/lynis/results #Lynis and results folders should be created on the dedicated server before executing this playbook
     delegate_to: ip_dedicated_server #Put here the IP address of your server

  - name: Send Lynis report
    copy:
     src: /var/log/{{ ansible_hostname }}-lynis-report.dat
     dest: /etc/lynis/results
     delegate_to: ip_dedicated_server